add solution for 01-button
js-tasks-ru/htmlcss-20210708_wise28 pull request #2
Opened 2021-07-06 11:28 UTC by wise28

2021-07-13 12:47 UTC, GSemikozov requested changes

2021-07-13 12:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    pointer-events: stroke;
лучше `none`

2021-07-13 12:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
`pointer` лучше пусть по умолчанию висит на .btn

2021-07-13 12:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: #fff;
еще в этом классе не определены другие параметры шрифта, такие как font-size и line-height (от чего, в том числе, зависит высота кнопки)

2021-07-13 12:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn-primary {
тут и ниже все модификаторы записываются через нижнее подчеркивание вместо дефиса (`.btn_primary`)

2021-07-14 10:06 UTC, wise28 commented on 03-lection1/01-button/button.css
> +.btn-primary {
тут можно поспорить)))если рассматривать с точки зрения отдельного класса, про примеру bootstrap, то можно записывать через дефис, а если с точки зрения модификатора бэм, то тогда через нижнее подчеркивание))))я делала отдельным классом кнопку, по примеру bootstrap))))

2021-07-14 12:35 UTC, wise28 commented on 03-lection1/01-button/button.css
> +    pointer-events: stroke;
тут он вообще оказывается не нужен. disabled регулируется js в данном случае, сразу не заметила. я его совсем уберу но я поняла почему none. наверное потому что none, только к svg применяется.

2021-07-14 13:47 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn-primary {
ноу, в курсе мы как раз и не делаем по примеру бутстрап (атомарные классы), мы все-таки используем БЭМ))

2021-07-18 18:49 UTC, closed without merging